      /IF NOT DEFINED(PROTOTYPE_MTOM01)
      *======================================================================
      *  Generated by WSDL2RPG 1.16.5 / 08.03.2017
      *  Built on Nov 1, 2017 (14:27:36)
      *  Built for V7R1M0
      *  Based on WS_SRV 1.16.5 - 08.03.2017
      *======================================================================
      *
      *   This source member contains the common procedures
      *   of web service port:
      *
      *      ArchiveServerPort
      *
      *======================================================================
      *   Pre-Compiler tags used by STRPREPRC to retrieve creation
      *   commands from the source member.
      * ---------------------------------------------------------------------
      * >>PRE-COMPILER<<
      *   >>CRTCMD<< CRTRPGMOD    MODULE(&LI/&OB) +
      *                           SRCFILE(&SL/&SF) +
      *                           SRCMBR(&SM);
      *   >>COMPILE<<
      *     >>PARM<< TRUNCNBR(*NO);
      *     >>PARM<< DBGVIEW(*LIST);
      *     >>PARM<< OPTION(*EVENTF);
      *   >>END-COMPILE<<
      *   >>EXECUTE<<
      *   >>CMD<<    CRTSRVPGM +
      *              SRVPGM(&LI/&OB ) +
      *              MODULE(&LI/&OB   +
      *                     &LI/MTOM01001        +
      *                     &LI/MTOM01002        +
      *                             ) +
      *              EXPORT(*ALL) +
      *              BNDSRVPGM(*LIBL/WSDL2RPGRT  +
      *                        *LIBL/MIME        +
      *                        *LIBL/HTTPMIME    +
      *                        *LIBL/BASICS1   ) +
      *              TEXT('+
      *              Web Service: ArchiveServerPort+
      *              ') +
      *              DETAIL(*BASIC);
      * >>END-PRE-COMPILER<<
      *======================================================================
     H NOMAIN
     H DEBUG
     H BNDDIR('HTTPAPI': 'QC2LE')
     H OPTION(*SRCSTMT : *NODEBUGIO)
     H EXTBININT(*YES)
      /ENDIF
      /IF NOT DEFINED(PROTOTYPE_DEFINED_MTOM01)
      /DEFINE PROTOTYPE_DEFINED_MTOM01
      *
      *   Type definitions
 CPY  /COPY QWSDL2RPG,TYPES_H
 CPY  /COPY QWSDL2RPG,PWSDL2R85                    WSDL2RPG: MessageContext
 CPY  /COPY QWSDL2RPG,PWSDL2R88                    WSDL2RPG: Public Helper Procedures
 CPY  /COPY QWSDL2RPG,PWSDL2R90                    WSDL2RPG: AppMsg
      *
      *   Array dimensions:
      *
      *   Web Service specific types:
     D tns_archiveFile_t...
     D                 DS                  likeds(tns_archiveFileRnmd_t)
     D                                     template
     D tns_archiveFileResponse_t...
     D                 DS                  likeds(tns_archiveFileResponseRnmd_t)
     D                                     template
      *
     D tns_archiveFileResponseRnmd_t...
     D                 DS                  template
     D                                     qualified
     D  return                      256A   varying
      *
      *
     D tns_archiveFileRnmd_t...
     D                 DS                  template
     D                                     qualified
     D  request                            likeds(tns_archiveRequest_t)
      *
      *
     D tns_archiveRequest_t...
     D                 DS                  template
     D                                     qualified
     D  description                 256A   varying
     D  fileLoad                    256A   varying
     D  fileName                    256A   varying
     D  fileType                    256A   varying
     D  key                         256A   varying
      *
     D tns_getFile_t   DS                  likeds(tns_getFileRnmd_t)
     D                                     template
     D tns_getFileResponse_t...
     D                 DS                  likeds(tns_getFileResponseRnmd_t)
     D                                     template
      *
     D tns_getFileResponseRnmd_t...
     D                 DS                  template
     D                                     qualified
     D  return                      256A   varying
      *
      *
     D tns_getFileRnmd_t...
     D                 DS                  template
     D                                     qualified
     D  key                         256A   varying
      *
      *   Public prototypes
      *
      *   Web service: Returns the endpoint of the Web service
     D ArchiveServerPort_Endpoint_get...
     D                 PR         32767A          varying
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_get+
     D                                     ')
      *
      *   Web service: Sets the endpoint of the Web service
     D ArchiveServerPort_Endpoint_set...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_set+
     D                                     ')
     D  i_url                     32767A   const varying  options(*varsize)
      *
      *   Web service: Returns the host name of the Web Service endpoint
     D ArchiveServerPort_Endpoint_getHost...
     D                 PR         32767A          varying
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_getHost+
     D                                     ')
      *
      *   Web service: Sets the host name of the Web service endpoint
     D ArchiveServerPort_Endpoint_setHost...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_setHost+
     D                                     ')
     D  i_url                     32767A   const varying  options(*varsize)
      *
      *   Web service: Returns the port of the Web Service endpoint
     D ArchiveServerPort_Endpoint_getPort...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_getPort+
     D                                     ')
      *
      *   Web service: Sets the port of the Web service endpoint
     D ArchiveServerPort_Endpoint_setPort...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Endpoint_setPort+
     D                                     ')
     D  i_port                       10I 0 const
      *
      *   Web service: Initializes the web services port
     D ArchiveServerPort_Port_initialize...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_initialize+
     D                                     ')
     D  i_operName                         const  like(wsdl_operName_t )
      *
      *   Web service: Sets the proxy server to use for the connection
     D ArchiveServerPort_Port_setHttpProxy...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setHttpProxy+
     D                                     ')
     D  i_server                    256A   const
     D  i_port                       10I 0 const
      *
      *   Web service: Returns the proxy server to use for the connection
     D ArchiveServerPort_Port_getHttpProxy...
     D                 PR                         likeds(wsdl_proxy_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getHttpProxy+
     D                                     ')
      *
      *   Web service: Enables/disables the debug log of HTTP API
     D ArchiveServerPort_Port_setHttpDebug...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setHttpDebug+
     D                                     ')
     D   i_status                      N   const
     D   i_fileName                 500A   const  varying  options(*nopass)
     D   i_verbose                     N   const  options(*nopass)
      *
      *   Web service: Returns the HTTP API debug settings
     D ArchiveServerPort_Port_getHttpDebug...
     D                 PR                         likeds(wsdl_httpDebug_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getHttpDebug+
     D                                     ')
      *
      *   Web service: Sets the CCSID used for POST data.
     D ArchiveServerPort_Port_setPostCcsid...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setPostCcsid+
     D                                     ')
     D  i_post_ccsid                 10I 0 const
      *
      *   Web service: Returns the CCSID used for POST data.
     D ArchiveServerPort_Port_getPostCcsid...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getPostCcsid+
     D                                     ')
      *
      *   Web service: Returns the XML encoding used for the SOAP message.
     D ArchiveServerPort_Port_getPostCcsidXml...
     D                 PR            20a   varying
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getPostCcsidXml+
     D                                     ')
      *
      *   Web service: Sets the timeout that HTTPAPI uses
      *   when connecting to the server or waiting for response.
     D ArchiveServerPort_Port_setTimeout...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setTimeout+
     D                                     ')
     D  i_timeout                    10I 0 const
      *
      *   Web service: Returns the timeout that HTTPAPI uses
      *   when connecting to the server or waiting for response.
     D ArchiveServerPort_Port_getTimeout...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getTimeout+
     D                                     ')
      *
      *   Web service: Sets the user-agent that HTTPAPI uses
      *   to identify the client at the server.
     D ArchiveServerPort_Port_setUserAgent...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setUserAgent+
     D                                     ')
     D  i_userAgent                        const  like(wsdl_userAgent_t )
      *
      *   Web service: Returns the user-agent that HTTPAPI uses
      *   to identify the client at the server.
     D ArchiveServerPort_Port_getUserAgent...
     D                 PR                         like(wsdl_userAgent_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getUserAgent+
     D                                     ')
      *
      *   Web service: Clears all error information
     D ArchiveServerPort_Port_clearErrors...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_clearErrors+
     D                                     ')
     D  io_errors                                 likeds(wsdl_errors_t )
      *
      *   Web service: Sets error information
     D ArchiveServerPort_Port_setErrors...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setErrors+
     D                                     ')
     D  i_errors                           const  likeds(wsdl_errors_t )
      *
      *   Http: Returns cTrue in case of an error, else cFalse.
     D ArchiveServerPort_Port_isError...
     D                 PR              N
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_isError+
     D                                     ')
      *
      *   Http: Returns the last HTTP error (code) that occurred.
     D ArchiveServerPort_HttpError_getCode...
     D                 PR                  like(wsdl_http_ErrorNo_t  )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _HttpError_getCode+
     D                                     ')
      *
      *   Http: Returns the last HTTP error (text) that occurred.
     D ArchiveServerPort_HttpError_getText...
     D                 PR                  like(wsdl_http_ErrorText_t)
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _HttpError_getText+
     D                                     ')
      *
      *   Soap: Returns the last SOAP error (code) that occurred.
     D ArchiveServerPort_SoapError_getCode...
     D                 PR                  like(wsdl_soap_faultcode_t  )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _SoapError_getCode+
     D                                     ')
      *
      *   Soap: Returns the last SOAP error (text) that occurred.
     D ArchiveServerPort_SoapError_getText...
     D                 PR                  like(wsdl_soap_faultstring_t)
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _SoapError_getText+
     D                                     ')
      *
      *   Soap: Returns the last XML error (code) that occurred.
     D ArchiveServerPort_XmlError_getCode...
     D                 PR                  like(wsdl_xml_errorNo_t    )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _XmlError_getCode+
     D                                     ')
      *
      *   Soap: Returns the last XML error (text) that occurred.
     D ArchiveServerPort_XmlError_getText...
     D                 PR                  like(wsdl_xml_ErrorText_t  )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _XmlError_getText+
     D                                     ')
      *
      *   Registers an user callback procedure, that is called whenever
      *   a web service requires user authentification.
     D ArchiveServerPort_Port_registerLoginCallback...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_registerLoginCallback+
     D                                     ')
     D  i_pLoginProc                   *   value  procptr
      *
      *   Returns *ON if a login procedures has been registered.
     D ArchiveServerPort_Port_hasLoginCallback...
     D                 PR              N
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_hasLoginCallback+
     D                                     ')
      *
      *   Sets the authentication type for a preemptive authentication.
     D ArchiveServerPort_Port_setPreemptiveAuthentication...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_setPreemptiveAuthentication+
     D                                     ')
     D  i_authType                    1A   value
     D  i_isProxyAuth                  N   value options(*nopass)
      *
      *   Returns cTrue if preemptive authentication is enabled.
     D ArchiveServerPort_Port_isAuthenticatePreemptively...
     D                 PR              N
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_isAuthenticatePreemptively+
     D                                     ')
      *
      *   Login preemptively to proxy server or web service.
     D ArchiveServerPort_Port_authenticatePreemptively...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_authenticatePreemptively+
     D                                     ')
      *
      *   Resets preemptive authentication.
     D ArchiveServerPort_Port_resetPreemptiveAuthentication...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_resetPreemptiveAuthentication+
     D                                     ')
      *
      *   Login to proxy server or web service.
     D ArchiveServerPort_Port_login...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_login+
     D                                     ')
     D  i_http_err                   10I 0 value
     D  i_numAttempts                10I 0 value
      *
      *   Returns the name of the web service port.
     D ArchiveServerPort_Port_getName...
     D                 PR           512A          varying
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getName+
     D                                     ')
      *
      *   Returns the UUID of the web service port.
     D ArchiveServerPort_Port_getUuid...
     D                 PR                         like(wsdl_uuid_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_getUuid+
     D                                     ')
      *
      *   Adds an attachments to the list of attachments.
     D ArchiveServerPort_Attachments_put...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_put+
     D                                     ')
     D  i_attachmentID...
     D                                     const  like(wsdl_attachmentID_t )
     D  i_fileName                         const  like(wsdl_path_t         )
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
      *   Returns the file name of the attachment that is associated to
      *   a given content ID.
     D ArchiveServerPort_Attachments_get...
     D                 PR                  like(wsdl_path_t     )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_get+
     D                                     ')
     D  i_attachmentID...
     D                                     const  like(wsdl_attachmentID_t )
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
      *   Returns the file name of the attachment that is associated to
      *   a given index.
     D ArchiveServerPort_Attachments_getAtPos...
     D                 PR                  likeds(wsdl_attachment_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_getAtPos+
     D                                     ')
     D  i_index                      10I 0 const
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
      *   Returns the number of attachments that were downloaded with the
      *   last call to the web service.
     D ArchiveServerPort_Attachments_getNumE...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_getNumE+
     D                                     ')
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
      *   Removes all attachments from the list of attachments of this web service.
     D ArchiveServerPort_Attachments_removeAll...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_removeAll+
     D                                     ')
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
      *   Specifies the name of the folder where to put attachments in.
     D ArchiveServerPort_Attachments_setFolder...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_setFolder+
     D                                     ')
     D  i_folder                           const  like(wsdl_pathLong_t )
      *
      *   Returns the name of the folder where attachments are stored.
     D ArchiveServerPort_Attachments_getFolder...
     D                 PR                         like(wsdl_pathLong_t )
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_getFolder+
     D                                     ')
      *
      *   Enables redirection of the HTTP response message to a
      *   stream file in the IFS.
     D ArchiveServerPort_RedirectResponse_toStmf...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _RedirectResponse_toStmf+
     D                                     ')
     D  i_stmf                             const  like(wsdl_pathLong_t )
     D  i_replace                      N   const  options(*nopass: *omit)
     D  i_ccsid                      10I 0 const  options(*nopass: *omit)
     D  i_auth                       10I 0 const  options(*nopass: *omit)
      *
      *   Returns cTrue if response redirection is active, otherwise cFalse.
     D ArchiveServerPort_RedirectResponse_isActive...
     D                 PR              N
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _RedirectResponse_isActive+
     D                                     ')
      *
      *   Terminates a response redirection and closes the
      *   file that receiced the response.
     D ArchiveServerPort_RedirectResponse_write...
     D                 PR              N
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _RedirectResponse_write+
     D                                     ')
     D  i_data                         *   value
     D  i_length                     10I 0 value
      *
      *   Terminates a response redirection and closes the
      *   file that receiced the response.
     D ArchiveServerPort_RedirectResponse_terminate...
     D                 PR
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _RedirectResponse_terminate+
     D                                     ')
      *
      * This procedure adds a file attachment. The attachment
      * is sent to the server the next time the web service is called.
     D ArchiveServerPort_Attachments_addFile...
     D                 PR                        like(wsdl_partID_t)
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_addFile+
     D                                     ')
     D  i_hMsgCtx                          const like(wsdl_hMsgCtx_t)
     D  i_path                             const like(wsdl_path_t)
     D  i_contentType                      const like(wsdl_contentType_t)
     D  i_transferEncoding...
     D                                     const like(
     D                                           wsdl_contentTransferEncoding_t)
     D                                           options(*nopass: *omit)
     D  i_suggestedFileName...
     D                                     const like(wsdl_path_t)
     D                                           options(*nopass: *omit)
      *
      * This procedure adds a buffer attachment. The attachment
      * is sent to the server the next time the web service is called.
     D ArchiveServerPort_Attachments_addBuffer...
     D                 PR                        like(wsdl_partID_t)
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Attachments_addBuffer+
     D                                     ')
     D  i_hMsgCtx                          const like(wsdl_hMsgCtx_t)
     D  i_name                             const like(wsdl_path_t)
     D  i_pBuffer                      *   const
     D  i_size                       10I 0 const
     D  i_contentType                      const like(wsdl_contentType_t)
     D  i_transferEncoding...
     D                                     const like(
     D                                           wsdl_contentTransferEncoding_t)
     D                                           options(*nopass: *omit)
     D  i_targetCcsid                10I 0 const options(*nopass: *omit)
      *
      /ENDIF
      /IF DEFINED(PROTOTYPE_MTOM01)
      /EOF
      /ENDIF
      * ---------------------------------------------------------------------
      *
      * ------------------------------------
      *  Imported prototypes
      * ------------------------------------
 CPY  /COPY QBASICS1,PBASICS1                      Tools/400 Runtime Library
 CPY  /COPY QRPGLESRC,HTTPAPI_H                    HTTP-API Service Program
      *
 CPY  /COPY QWSDL2RPG,PWSDL2R71                    WSDL2RPG: HTTP Debug Log
 CPY  /COPY QWSDL2RPG,PWSDL2R89                    WSDL2RPG: List of Attachments
      *
      * ------------------------------------
      *  Internal prototypes
      * ------------------------------------
      *
     D getEndpoint...
     D                 PR         32767A          varying
     D                                     extproc('+
     D                                     getEndpoint+
     D                                     ')
      *
     D setEndpoint...
     D                 PR
     D                                     extproc('+
     D                                     setEndpoint+
     D                                     ')
     D  i_url                     32767A   const varying  options(*varsize)
      *
     D loginInternally...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     loginInternally+
     D                                     ')
     D  i_authTarget                 14A   value varying
     D  i_authType                    1A   value
     D  i_realm                     124A   value
     D  i_numAttempts                10I 0 value
      *
      * ------------------------------------
      *  Global fields & constants
      * ------------------------------------
      *
      *   Web service port name
     D cWEB_SERVICE_PORT_NAME...
     D                 C                   'ArchiveServerPort'
      *
      *   UUID of the web service as generated by WSDL2RPG
     D cWEB_SERVICE_UUID...
     D                 C                   '1239B801EB7119FF9FDD0004AC18DB29'
      *
      *   Default and current attachment folder
     D cATTACHMENT_FOLDER...
     D                 C                   '/tmp/attachments/'
      *
      *   Default POST data CCSID (1208 = UTF-8)
     D cPOST_DATA_CCSID...
     D                 C                   1208
      *
      *   Web service endpoint as specified in the WSDL file.
     D cURL            C                   'http://localhost:10000/MTOMService/+
     D                                     services/archiveServer'
      *
      *   Web service endpoint
     D g_url           S          32767A   varying inz(cURL)
      *
      *   Proxy server to use
     D g_proxy         DS                  likeds(wsdl_proxy_t     ) inz
      *
      *   HTTPAPI debug settings
     D g_httpDebug     DS                  likeds(wsdl_httpDebug_t ) inz
      *
      *   POST data CCSID (1208 = UTF-8)
     D g_post_ccsid...
     D                 S             10I 0 inz(cPOST_DATA_CCSID)
      *
      *   Timeout in seconds used when connecting to the server
      *   or waiting for response from the server.
     D g_timeout...
     D                 S             10I 0 inz(HTTP_TIMEOUT)
      *
      *   User-agent used when connecting to the server.
     D g_userAgent...
     D                 S                   like(wsdl_userAgent_t )
     D                                     inz(HTTP_USERAGENT)
      *
      *   Name of the directory used to store attachments
     D g_attachmentFolder...
     D                 S                   like(wsdl_pathLong_t )
     D                                     inz(cATTACHMENT_FOLDER)
      *
      *   Redirect response status information
     D g_redirectResponse...
     D                 DS                  qualified
     D  isActive                       N   inz(cFalse)
     D  ccsid                        10I 0 inz
     D  auth                         10I 0 inz
     D  options                      10I 0 inz
     D  fd                           10I 0 inz(-1)
     D  path                               like(wsdl_pathLong_t ) inz
      *
      *   Authenticate pre-emptively
     D g_authenticatePreemptively...
     D                 DS                  qualified
     D  isActive                       N   inz(cFalse)
     D  authType                      1A   inz
     D  isProxyAuth                    N   inz(cFalse)
      *
      *   Web service error information
     D g_errors        DS                  likeds(wsdl_errors_t    ) inz
      *
      *   User callback to supply login information
      *   Returns WSDL_SUCCESS if successful, WSDL_ERROR upon error.
     D g_getLoginDataImpl...
     D                 S               *   procptr inz
      *
      *   User callback to supply login information
      *   Returns WSDL_SUCCESS if successful, WSDL_ERROR upon error.
      *
      *   Parameter description:
      *     i_authType         Authentication type:
      *                          WSDL_AUTH_TYPE_HTTP  - HTTP server.
      *                          WSDL_AUTH_TYPE_PROXY - Proxy server.
      *     i_realm            Authentication realm.
      *                        For preemptive authentication, 'WSDL-PRE-EMPTIVE'
      *                        is passed to the login procedure.
      *     i_numAttempts      Number of login attempts.
      *     o_user             UserName to use.
      *     o_password         Password to use.
      *
     D ArchiveServerPort_Port_supplyLoginData...
     D                 PR            10I 0
     D                                     extproc('+
     D                                     ArchiveServerPort+
     D                                     _Port_supplyLoginData+
     D                                     ')
     D  i_authType                   14A          const  varying
     D  i_realm                     126A          const  varying
     D  i_numAttempts                10I 0        const
     D  o_user                                           like(wsdl_user_t)
     D  o_password                                       like(wsdl_password_t)
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the endpoint of the Web service
      * =====================================================================
     P ArchiveServerPort_Endpoint_get...
     P                 B                   export
     D                 PI         32767A          varying
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return getEndpoint();

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the endpoint of the Web service
      * =====================================================================
     P ArchiveServerPort_Endpoint_set...
     P                 B                   export
     D                 PI
     D  i_url                     32767A   const varying  options(*varsize)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         setEndpoint(%subst(i_url: 1: %len(i_url)));

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the host name of the Web Service endpoint
      * =====================================================================
     P ArchiveServerPort_Endpoint_getHost...
     P                 B                   export
     D                 PI         32767A          varying
      *
     D tmpUrl          S                   like(url_t ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         tmpUrl = URL_new(getEndpoint());

         return URL_getHost(tmpUrl);

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the host name of the Web service endpoint
      * =====================================================================
     P ArchiveServerPort_Endpoint_setHost...
     P                 B                   export
     D                 PI
     D  i_host                    32767A   const varying  options(*varsize)
      *
     D tmpUrl          S                   like(url_t ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         tmpUrl = URL_new(getEndpoint());
         URL_setHost(tmpUrl: %subst(i_host: 1: %len(i_host)));
         setEndpoint(URL_toString(tmpUrl));

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the port of the Web Service endpoint
      * =====================================================================
     P ArchiveServerPort_Endpoint_getPort...
     P                 B                   export
     D                 PI            10I 0
      *
     D tmpUrl          S                   like(url_t ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         tmpUrl = URL_new(getEndpoint());

         return URL_getPort(tmpUrl);

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the port of the Web service endpoint
      * =====================================================================
     P ArchiveServerPort_Endpoint_setPort...
     P                 B                   export
     D                 PI
     D  i_port                       10I 0 const
      *
     D tmpUrl          S                   like(url_t ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         tmpUrl = URL_new(getEndpoint());
         URL_setPort(tmpUrl: i_port);
         setEndpoint(URL_toString(tmpUrl));

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Web service: Initializes the web service port.
      * =====================================================================
     P ArchiveServerPort_Port_initialize...
     P                 B                   export
     D                 PI
     D  i_operName                         const  like(wsdl_operName_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         // This procedure is called from every web service
         // operation right at the beginning of the operation.
         // This procedure may be used to perform any type
         // of initialization that is the same for all web
         // service operations.
         // For example you may want to register a procedure
         // to supply login credentials like this:

 B01     if (not ArchiveServerPort_Port_hasLoginCallback());
            ArchiveServerPort_Port_registerLoginCallback(
               %paddr('+
                  ArchiveServerPort_Port_supplyLoginData+
               '));
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by *_Port_login() ***
      *   Web service: Supplies login credentials for web services that
      *                require BASIC or DIGEST authentication.
      * =====================================================================
     P ArchiveServerPort_Port_supplyLoginData...
     P                 B                   export
     D                 PI            10I 0
     D  i_authType                   14A          const  varying
     D  i_realm                     126A          const  varying
     D  i_numAttempts                10I 0        const
     D  o_user                                           like(wsdl_user_t)
     D  o_password                                       like(wsdl_password_t)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         // This procedure is called when a web service requires
         // BASIC or DIGEST authentication.
         // You may use the realm value for reading the credentials
         // from a file. Make sure that you do not get into an endless
         // loop in case the credentials are retrieved from a file.
         // The credentials might be wrong!

         // Prevent endless loop when reading the credentials from a file
         // You may remove this IF statement when a user enters the
         // credentials.
 B01     if (i_numAttempts > 1);
            return WSDL_ERROR;
 E01     endif;

         // Set o_user and o_password here and remove the error message.
         // Return WSDL_SUCCESS to let the caller know that user and
         // password have been set, otherwise return WSDL_ERROR.

         clear USR0048;
         USR00481 = f_this();
         AppMsg_sendCancelMsg(AppMsg_newError('USR0048': USR0048));

         return WSDL_ERROR;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the proxy server to use for the connection
      * =====================================================================
     P ArchiveServerPort_Port_setHttpProxy...
     P                 B                   export
     D                 PI
     D  i_server                    256A   const
     D  i_port                       10I 0 const
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_proxy.server = i_server;

 B01     if (g_proxy.server = '');
            g_proxy.port = 0;
 X01     else;
            g_proxy.port = i_port;
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the proxy server to use for the connection
      * =====================================================================
     P ArchiveServerPort_Port_getHttpProxy...
     P                 B                   export
     D                 PI                         likeds(wsdl_proxy_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_proxy;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Enables/disables the debug log of HTTP API
      * =====================================================================
     P ArchiveServerPort_Port_setHttpDebug...
     P                 B                   export
     D                 PI
     D   i_status                      N   const
     D   i_fileName                 500A   const  varying  options(*nopass)
     D   i_verbose                     N   const  options(*nopass)
      *
      *  Parameter positions
     D p_fileName      C                   2
     D p_verbose       C                   3
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_httpDebug.status = i_status;

 B01     if (%parms() >= p_fileName);
            g_httpDebug.fileName = i_fileName;
 X01     else;
            g_httpDebug.fileName = '';
 E01     endif;

 B01     if (i_status);
 B02        if (g_httpDebug.fileName = '');
               g_httpDebug.fileName = HTTP_API_DEFAULT_LOG_FILE;
 E02        endif;
 X01     else;
            g_httpDebug.fileName = '';
 E01     endif;

 B01     if (i_status);
            http_DebugLog_open(g_httpDebug.fileName);
 X01     else;
            http_DebugLog_close();
 E01     endif;

 B01     if (%parms() >= p_verbose);
            http_DebugLog_setVerbose(i_verbose);
 X01     else;
            http_DebugLog_setVerbose(cFalse);
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the HTTP API debug settings
      * =====================================================================
     P ArchiveServerPort_Port_getHttpDebug...
     P                 B                   export
     D                 PI                         likeds(wsdl_httpDebug_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (g_httpDebug.fileName = '');
            g_httpDebug.fileName = HTTP_API_DEFAULT_LOG_FILE;
 E01     endif;

         return g_httpDebug;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the CCSID used for POST data.
      *   An application may call this procedure right before the web service
      *   operation in order to specify a POST ccsid different from 1208.
      *   Usually it is not necessary to call this procedure.
      * =====================================================================
     P ArchiveServerPort_Port_setPostCcsid...
     P                 B                   export
     D                 PI
     D  i_post_ccsid                 10I 0 const
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (i_post_ccsid <> 1208 and i_post_ccsid <> 1200);
            http_DebugLog_appendText(
               '** Warning: According to the ''Basic Profile Version 1.0'' +
                specification, CCSID ' + %char(i_post_ccsid) +
               ' is not allowed. See chapter +
                4.1.11 Acceptable SOAP Character Encodings.');
 E01     endif;

         g_post_ccsid = i_post_ccsid;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the CCSID used for POST
      * =====================================================================
     P ArchiveServerPort_Port_getPostCcsid...
     P                 B                   export
     D                 PI            10I 0
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_post_ccsid;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the XML encoding used for the SOAP message.
      * =====================================================================
     P ArchiveServerPort_Port_getPostCcsidXml...
     P                 B                   export
     D                 PI            20a   varying
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     select;
 X01     when (g_post_ccsid = 1200);
            return 'utf-16';
 X01     when (g_post_ccsid = 1208);
            return 'utf-8';
 X01     other;
            return 'ibm-' + %char(g_post_ccsid);
 E01     endsl;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the timeout that HTTPAPI uses
      *   when connecting to the server or waiting for response.
      *   Usually it is not necessary to call this procedure.
      * =====================================================================
     P ArchiveServerPort_Port_setTimeout...
     P                 B                   export
     D                 PI
     D  i_timeout                    10I 0 const
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_timeout = i_timeout;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the timeout that HTTPAPI uses
      *   when connecting to the server or waiting for response.
      * =====================================================================
     P ArchiveServerPort_Port_getTimeout...
     P                 B                   export
     D                 PI            10I 0
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_timeout;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Sets the user-agent that HTTPAPI uses
      *   to identify the client at the server.
      *   Usually it is not necessary to call this procedure.
      * =====================================================================
     P ArchiveServerPort_Port_setUserAgent...
     P                 B                   export
     D                 PI
     D  i_userAgent                        const  like(wsdl_userAgent_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_userAgent = i_userAgent;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Web service: Returns the user-agent that HTTPAPI uses
      *   to identify the client at the server.
      * =====================================================================
     P ArchiveServerPort_Port_getUserAgent...
     P                 B                   export
     D                 PI                         like(wsdl_userAgent_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_userAgent;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Web service: Clears all error information.
      * =====================================================================
     P ArchiveServerPort_Port_clearErrors...
     P                 B                   export
     D                 PI
     D  io_errors                                 likeds(wsdl_errors_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         clear g_errors;
         g_errors.errType = WSDL_HTTP_SUCCESS;

         io_errors = g_errors;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Web service: Sets error information of last service call.
      * =====================================================================
     P ArchiveServerPort_Port_setErrors...
     P                 B                   export
     D                 PI
     D  i_errors                           const  likeds(wsdl_errors_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_errors = i_errors;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Http: Returns the last HTTP error (code) that occurred.
      *   An application should use this procedure to check whether or not
      *   the web service operation has bee successfully executed.
      * =====================================================================
     P ArchiveServerPort_Port_isError...
     P                 B                   export
     D                 PI              N
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (g_errors.errType = WSDL_HTTP_SUCCESS);
            return cFalse;
 X01     else;
            return cTrue;
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Http: Returns the last HTTP error (code) that occurred.
      * =====================================================================
     P ArchiveServerPort_HttpError_getCode...
     P                 B                   export
     D                 PI                  like(wsdl_http_ErrorNo_t  )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.httpError.no;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Http: Returns the last HTTP error (text) that occurred.
      * =====================================================================
     P ArchiveServerPort_HttpError_getText...
     P                 B                   export
     D                 PI                  like(wsdl_http_ErrorText_t)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.httpError.text;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Soap: Returns the last SOAP error (code) that occurred.
      * =====================================================================
     P ArchiveServerPort_SoapError_getCode...
     P                 B                   export
     D                 PI                  like(wsdl_soap_faultcode_t  )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.soapFault.code;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Soap: Returns the last SOAP error (text) that occurred.
      * =====================================================================
     P ArchiveServerPort_SoapError_getText...
     P                 B                   export
     D                 PI                  like(wsdl_soap_faultstring_t)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.soapFault.string;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   XML: Returns the last XML error (code) that occurred.
      * =====================================================================
     P ArchiveServerPort_XmlError_getCode...
     P                 B                   export
     D                 PI                  like(wsdl_xml_ErrorNo_t    )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.xmlError.code;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   XML: Returns the last XML error (text) that occurred.
      * =====================================================================
     P ArchiveServerPort_XmlError_getText...
     P                 B                   export
     D                 PI                  like(wsdl_xml_ErrorText_t  )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_errors.xmlError.text;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Registers an user callback procedure, that is called whenever
      *   a web service requires user authentification.
      *   An application may call this procedure in order to register a
      *   user and password provider different from *_Port_supplyLoginData().
      *   Usually *_Port_supplyLoginData() should be modified to match the
      *   requirements of the application.
      * =====================================================================
     P ArchiveServerPort_Port_registerLoginCallback...
     P                 B                   export
     D                 PI
  D  D  i_pLoginProc                   *   value  procptr
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_getLoginDataImpl = i_pLoginProc;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns *ON if a login procedures has been registered.
      *   This procedure is used by WS_OPER() but might also be called
      *   by the application to see whether or not a user and password
      *   provider is present.
      * =====================================================================
     P ArchiveServerPort_Port_hasLoginCallback...
     P                 B                   export
     D                 PI              N
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (g_getLoginDataImpl <> *NULL);
            return *ON;
 E01     endif;

         return *OFF;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Sets the authentication type for a preemptive authentication.
      * =====================================================================
     P ArchiveServerPort_Port_isAuthenticatePreemptively...
     P                 B                   export
     D                 PI              N
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_authenticatePreemptively.isActive;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Returns cTrue if preemptive authentication is enabled.
      * =====================================================================
     P ArchiveServerPort_Port_setPreemptiveAuthentication...
     P                 B                   export
     D                 PI
     D  i_authType                    1A   value
     D  i_isProxyAuth                  N   value options(*nopass)
      *
      *  Parameter positions
     D p_isProxyAuth   C                   2
      *
      *  Optional parameters
     D isProxyAuth     S                   like(i_isProxyAuth)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_isProxyAuth and %addr(i_isProxyAuth) <> *NULL);
            isProxyAuth = i_isProxyAuth;
 X01     else;
            isProxyAuth = cFalse;
 E01     endif;

         g_authenticatePreemptively.isActive = cTrue;
         g_authenticatePreemptively.authType = i_authType;
         g_authenticatePreemptively.isProxyAuth = isProxyAuth;

         http_DebugLog_appendText(
            '** '+ %char(%timestamp()) +': Preemptive authentication +
                                           switched on');

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Login preemptively to proxy server or web service.
      * =====================================================================
     P ArchiveServerPort_Port_authenticatePreemptively...
     P                 B                   export
     D                 PI            10I 0
      *
      *  Return value
     D rc              S             10I 0 inz
      *
      *  Helper fields
     D authTarget      S             14A   inz varying
     D authType        S              1A   inz
     D realm           S            124A   inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (not g_authenticatePreemptively.isProxyAuth);
            authTarget = WSDL_AUTH_TYPE_HTTP;
 X01     else;
            authTarget = WSDL_AUTH_TYPE_PROXY;
 E01     endif;

         authType = g_authenticatePreemptively.authType;
         realm = WSDL_REALM_PREEMPTIVE_AUTHENTICATION;

         http_DebugLog_appendText(
            '** '+ %char(%timestamp()) +': Authenticating preemptively');

         rc = loginInternally(authTarget: authType: realm: 1);

         return rc;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Resets preemptive authentication.
      * =====================================================================
     P ArchiveServerPort_Port_resetPreemptiveAuthentication...
     P                 B                   export
     D                 PI
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (g_authenticatePreemptively.isActive);
            g_authenticatePreemptively.isActive = cFalse;
            g_authenticatePreemptively.authType = '';
            g_authenticatePreemptively.isProxyAuth = cFalse;

            http_DebugLog_appendText(
               '** '+ %char(%timestamp()) +': Preemptive authentication +
                                              switched off');
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Login to proxy server or web service.
      * =====================================================================
     P ArchiveServerPort_Port_login...
     P                 B                   export
     D                 PI            10I 0
     D  i_http_err                   10I 0 value
     D  i_numAttempts                10I 0 value
      *
      *  Return value
     D rc              S             10I 0 inz
      *
      *  Helper fields
     D basic           S               N   inz
     D digest          S               N   inz
     D realm           S            124A   inz
     D authType        S              1A   inz
     D authTarget      S             14A   inz varying
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (i_http_err = HTTP_NDAUTH);
            http_getauth(basic: digest: realm);
            authTarget = WSDL_AUTH_TYPE_HTTP;
 X01     else;
            http_proxy_getauth(basic: realm);
            authTarget = WSDL_AUTH_TYPE_PROXY;
 E01     endif;

 B01     select;
 X01     when (digest);
            authType = HTTP_AUTH_MD5_DIGEST;
 X01     when (basic);
            authType = HTTP_AUTH_BASIC;
 X01     other;
            authType = WSDL_AUTH_NTLM;
 E01     endsl;

         http_DebugLog_appendText(
            '** '+ %char(%timestamp()) +': attempting to authenticate. ' +
                                        '£' + %char(i_numAttempts) + ' try.');

         rc = loginInternally(authTarget: authType: realm: i_numAttempts);

         return rc;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private
      *   Login to proxy server or web service.
      * =====================================================================
     P loginInternally...
     P                 B
     D                 PI            10I 0
     D  i_authTarget                 14A   value varying
     D  i_authType                    1A   value
     D  i_realm                     124A   value
     D  i_numAttempts                10I 0 value
      *
      *  Return value
     D rc              S             10I 0 inz
      *
     D getLoginDataImpl...
     D                 PR            10I 0
     D                                     extproc(g_getLoginDataImpl)
     D  i_authType                   14A          const  varying
     D  i_realm                     126A          const  varying
     D  i_numAttempts                10I 0        const
     D  o_user                                           like(wsdl_user_t)
     D  o_password                                       like(wsdl_password_t)
      *
     D userid          S                   like(wsdl_user_t) inz
     D password        S                   like(wsdl_password_t) inz
     D authErr         S             10I 0 inz
     D err             S             10I 0 inz
     D errText         S             80A   inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         rc = getLoginDataImpl(i_authTarget: i_realm
                               : i_numAttempts: userid: password);
 B01     if (rc <> 1);
            userid = '';
            password = '';
            return rc;
 E01     endif;

 B01     if (i_authTarget = WSDL_AUTH_TYPE_HTTP);
 B02        select;
 X02        when (i_authType = HTTP_AUTH_MD5_DIGEST);
               authErr = http_setAuth(HTTP_AUTH_MD5_DIGEST
                                      : userid: password);
 X02        when (i_authType = HTTP_AUTH_BASIC);
               authErr = http_setAuth(HTTP_AUTH_BASIC
                                      : userid: password);
 X02        other;
               authErr = http_setAuth(WSDL_AUTH_NTLM
                                      : userid: password);
 E02        endsl;
 X01     else;
 B02        select;
 X02        when (i_authType = HTTP_AUTH_MD5_DIGEST);
               authErr = http_proxy_setAuth(HTTP_AUTH_MD5_DIGEST
                                            : userid: password);
 X02        when (i_authType = HTTP_AUTH_BASIC);
               authErr = http_proxy_setAuth(HTTP_AUTH_BASIC
                                            : userid: password);
 X02        other;
               // not yet supported
               http_DebugLog_appendText(
                  '** NTLM authentication is not supported +
                   for proxy authentication');
               authErr = -1;
 E02        endsl;
 E01     endif;

 B01     if (authErr = -1);
            errText = http_error(err);
            http_DebugLog_appendText('** Failed to login: ' + errText);
 B02        if (i_authType = WSDL_AUTH_NTLM);
               http_DebugLog_appendText('** Your version of HTTPAPI +
                                         does not support NTLM authentication');
 E02        endif;
            rc = WSDL_ERROR;
 E01     endif;

         userid = '';
         password = '';

         return rc;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns the name of the web service port.
      *   This procedure is used by WS_OPER() but might also be called
      *   by the application for information purposes.
      * =====================================================================
     P ArchiveServerPort_Port_getName...
     P                 B                   export
     D                 PI                         like(wsdl_portName_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return cWEB_SERVICE_PORT_NAME;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Returns the UUID of the web service port.
      * =====================================================================
     P ArchiveServerPort_Port_getUuid...
     P                 B                   export
     D                 PI                         like(wsdl_uuid_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return cWEB_SERVICE_UUID;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Adds an attachments to the list of attachments.
      * =====================================================================
     P ArchiveServerPort_Attachments_put...
     P                 B                   export
     D                 PI
     D  i_attachmentID...
     D                                     const  like(wsdl_attachmentID_t )
     D  i_fileName                         const  like(wsdl_path_t         )
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
     D p_uuid          C                   3
      *
     D uuid            S                   like(i_uuid          ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_uuid);
            uuid = i_uuid;
 X01     else;
            uuid = ArchiveServerPort_Port_getUuid();
 E01     endif;

         Attachments_put(Attachments_theInstance()
                         : uuid
                         : i_attachmentID
                         : i_fileName);

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns the file name of the attachment that is associated to
      *   a given content ID.
      *   An application can use this procedure to get an attachments
      *   of the last web service operation.
      * =====================================================================
     P ArchiveServerPort_Attachments_get...
     P                 B                   export
     D                 PI                  like(wsdl_path_t     )
     D  i_attachmentID...
     D                                     const  like(wsdl_attachmentID_t )
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
     D p_uuid          C                   2
      *
     D uuid            S                   like(i_uuid          ) inz
     D fileName        S                   like(wsdl_path_t     ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_uuid);
            uuid = i_uuid;
 X01     else;
            uuid = ArchiveServerPort_Port_getUuid();
 E01     endif;

         fileName = Attachments_get(Attachments_theInstance()
                                    : uuid
                                    : i_attachmentID);
         return fileName;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns the file name of the attachment that is associated to
      *   a given index.
      *   An application can use this procedure to get an attachments
      *   of the last web service operation.
      * =====================================================================
     P ArchiveServerPort_Attachments_getAtPos...
     P                 B                   export
     D                 PI                  likeds(wsdl_attachment_t )
     D  i_index                      10I 0 const
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
     D p_uuid          C                   2
      *
     D uuid            S                   like(i_uuid          ) inz
     D attachment      DS                  likeds(wsdl_attachment_t ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_uuid);
            uuid = i_uuid;
 X01     else;
            uuid = ArchiveServerPort_Port_getUuid();
 E01     endif;

         attachment = Attachments_getAtPos(Attachments_theInstance()
                                           : uuid
                                           : i_index);
         return attachment;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns the number of attachments that were downloaded with
      *   the last call of the web service.
      * =====================================================================
     P ArchiveServerPort_Attachments_getNumE...
     P                 B                   export
     D                 PI            10I 0
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
     D p_uuid          C                   1
      *
     D uuid            S                   like(i_uuid          ) inz
     D numE            S             10I 0 inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_uuid);
            uuid = i_uuid;
 X01     else;
            uuid = ArchiveServerPort_Port_getUuid();
 E01     endif;

         numE = Attachments_getNumAttachments(
                      Attachments_theInstance(): uuid);

         return numE;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Removes all attachments from the list of attachments of
      *   this web service.
      *   An application should call this procedure once that the
      *   attachments of the last web service operation are obsolete.
      *   This procedure is also used by WS_OPER() to remove all attachments
      *   before the next web service call.
      * =====================================================================
     P ArchiveServerPort_Attachments_removeAll...
     P                 B                   export
     D                 PI
     D  i_uuid                             const  like(wsdl_uuid_t         )
     D                                            options(*nopass)
      *
     D p_uuid          C                   1
      *
     D uuid            S                   like(i_uuid          ) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_uuid);
            uuid = i_uuid;
 X01     else;
            uuid = ArchiveServerPort_Port_getUuid();
 E01     endif;

         Attachments_removeAll(Attachments_theInstance(): uuid);

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Specifies the name of the folder where to put attachments in.
      *   An application may use this procedure to specify a folder where
      *   to store attachements. The default value is '/tmp/attachments/'.
      * =====================================================================
     P ArchiveServerPort_Attachments_setFolder...
     P                 B                   export
     D                 PI
     D  i_folder                           const  like(wsdl_pathLong_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_attachmentFolder = i_folder;

         g_attachmentFolder = %trimR(%xlate('Ö': '/': g_attachmentFolder));
 B01     if (not f_endsWith('/': g_attachmentFolder));
            g_attachmentFolder = g_attachmentFolder + '/';
 E01     endif;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Returns the name of the folder where attachments are stored.
      * =====================================================================
     P ArchiveServerPort_Attachments_getFolder...
     P                 B                   export
     D                 PI                         like(wsdl_pathLong_t )
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_attachmentFolder;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** public ***
      *   Enables redirection of the HTTP response message to a
      *   stream file in the IFS.
      * =====================================================================
     P ArchiveServerPort_RedirectResponse_toStmf...
     P                 B                   export
     D                 PI
     D  i_stmf                             const  like(wsdl_pathLong_t )
     D  i_replace                      N   const  options(*nopass: *omit)
     D  i_ccsid                      10I 0 const  options(*nopass: *omit)
     D  i_auth                       10I 0 const  options(*nopass: *omit)
      *
      *  Parameter positions
     D p_replace       C                   2
     D p_ccsid         C                   3
     D p_auth          C                   4
      *
      *  Optional parameter fields
     D replace         S                   like(i_replace ) inz
     D ccsid           S                   like(i_ccsid   ) inz
     D auth            S                   like(i_auth    ) inz
      *
      *  Helper fields
     D options         S             10I 0 inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         ArchiveServerPort_RedirectResponse_terminate();

 B01     if (%trim(i_stmf) = '');
            g_redirectResponse.isActive = cFalse;
            g_redirectResponse.ccsid    = 0;
            g_redirectResponse.auth     = 0;
            g_redirectResponse.options  = 0;
            g_redirectResponse.fd       = -1;
            g_redirectResponse.path     = '';
            return;
 E01     endif;

         http_DebugLog_appendText(
         '** Response redirected to: ' + i_stmf);

 B01     if (%parms() >= p_replace and %addr(i_replace) <> *NULL);
            replace = i_replace;
 X01     else;
            replace = cFalse;
 E01     endif;

 B01     if (%parms() >= p_ccsid and %addr(i_ccsid) <> *NULL);
            ccsid = i_ccsid;
 X01     else;
            ccsid = 1208;   // UTF-8
 E01     endif;

 B01     if (%parms() >= p_auth and %addr(i_auth) <> *NULL);
            auth = i_auth;
 X01     else;
            auth = S_IRWXU + S_IRWXG + S_IRWXO;
 E01     endif;

         options = O_CREAT + O_SHARE_RDONLY + O_WRONLY + O_CCSID;
 B01     if (replace);
            options = options + O_TRUNC;
 X01     else;
            options = options + O_APPEND;
 E01     endif;

         g_redirectResponse.isActive = cTrue;
         g_redirectResponse.ccsid    = ccsid;
         g_redirectResponse.auth     = auth;
         g_redirectResponse.options  = options;
         g_redirectResponse.fd       = -1;
         g_redirectResponse.path     = i_stmf;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Returns cTrue if response redirection is active, otherwise cFalse.
      * =====================================================================
     P ArchiveServerPort_RedirectResponse_isActive...
     P                 B                   export
     D                 PI              N
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_redirectResponse.isActive;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Terminates a response redirection and closes the
      *   file that receiced the response.
      * =====================================================================
     P ArchiveServerPort_RedirectResponse_write...
     P                 B                   export
     D                 PI              N
     D  i_data                         *   value
     D  i_length                     10I 0 value
      *
     D doAddCRLF       S               N   inz(cFalse)
     D CRLF            S              2A   inz(cEBCDIC_CRLF)
     D ascii           DS                  qualified
     D  pCRLF                          *   inz
     D  size                         10I 0 inz
     D st_stat         DS                  likeds(st_stat_t) inz
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         // Add CRLF, when the stream file exists to start the
         // XML at the next line.
 B01     if (stat(g_redirectResponse.path: %addr(st_stat)) = 0 and
             st_stat.size > 0);
            doAddCRLF = cTrue;
 X01     else;
            doAddCRLF = cFalse;
 E01     endif;

         // Open output file
 B01     if (g_redirectResponse.fd = -1);
            g_redirectResponse.fd = open(g_redirectResponse.path
                                        : g_redirectResponse.options
                                        : g_redirectResponse.auth
                                        : g_redirectResponse.ccsid);
 B02        if (g_redirectResponse.fd = -1);
               http_DebugLog_appendText(
               '** '+ %char(%timestamp()) +': Failed to open: ' +
                                              g_redirectResponse.path);
               return cFalse;
 E02        endif;
 E01     endif;

 B01     if (doAddCRLF);
            ascii.size = HTTP_xlatedyn(%size(CRLF): %addr(CRLF)
                                       : TO_ASCII: ascii.pCRLF);
            callp write(g_redirectResponse.fd: ascii.pCRLF: ascii.size);
            dealloc(N) ascii.pCRLF;
            clear ascii;
 E01     endif;

         // Append data to output file
 B01     if (write(g_redirectResponse.fd: i_data: i_length) <> i_length);
               http_DebugLog_appendText(
               '** '+ %char(%timestamp()) +': Failed to append ' +
                                              %char(i_length) + ' bytes to: ' +
                                              g_redirectResponse.path);
            return cFalse;
 E01     endif;

         return cTrue;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      *   Terminates a response redirection and closes the
      *   file that receiced the response.
      * =====================================================================
     P ArchiveServerPort_RedirectResponse_terminate...
     P                 B                   export
     D                 PI
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (g_redirectResponse.fd <> -1);
            callp close(g_redirectResponse.fd);
            g_redirectResponse.fd = -1;
 E01     endif;

         g_redirectResponse.path = '';
         g_redirectResponse.isActive = cFalse;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      * This procedure adds a file attachment. The attachment
      * is sent to the server the next time the web service is called.
      * =====================================================================
     P ArchiveServerPort_Attachments_addFile...
     P                 B                   export
     D                 PI                        like(wsdl_partID_t)
     D  i_hMsgCtx                          const like(wsdl_hMsgCtx_t)
     D  i_path                             const like(wsdl_path_t)
     D  i_contentType                      const like(wsdl_contentType_t)
     D  i_transferEncoding...
     D                                     const like(
     D                                           wsdl_contentTransferEncoding_t)
     D                                           options(*nopass: *omit)
     D  i_suggestedFileName...
     D                                     const like(wsdl_path_t)
     D                                           options(*nopass: *omit)
      *
      *  Return value
     D partID          S                   like(wsdl_partID_t) inz
      *
      *  Parameter positions
     D p_transferEncoding...
     D                 C                   4
     D p_suggestedFileName...
     D                 C                   5
      *
      *  Optional parameters
     D transferEncoding...
     D                 S                   like(i_transferEncoding)
     D suggestedFileName...
     D                 S                   like(i_suggestedFileName)
      *
      *  Local fields
     D hDataSource     S                   like(wsdl_hDataSource_t)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_transferEncoding and
             %addr(i_transferEncoding) <> *NULL);
            transferEncoding = i_transferEncoding;
 X01     else;
            transferEncoding = WSDL_MIME_BINARY;
 E01     endif;

 B01     if (%parms() >= p_suggestedFileName and
             %addr(i_suggestedFileName) <> *NULL);
            suggestedFileName = i_suggestedFileName;
 X01     else;
            suggestedFileName = File_getName(i_path);
 E01     endif;

         // Create datasource that points to the file
         hDataSource = ManagedMemoryDataSource_new();
         ManagedMemoryDataSource_setPath(hDataSource: i_path: i_contentType);

         // Add attachment to message context
         partID =
            MessageContext_addAttachment(
               i_hMsgCtx: hDataSource: transferEncoding: suggestedFileName);

         return partID;

      /end-free
     P                 E
      *
      * =====================================================================
      *   *** private, automatically called by WS_OPER() ***
      * This procedure adds a buffer attachment. The attachment
      * is sent to the server the next time the web service is called.
      * =====================================================================
     P ArchiveServerPort_Attachments_addBuffer...
     P                 B                   export
     D                 PI                        like(wsdl_partID_t)
     D  i_hMsgCtx                          const like(wsdl_hMsgCtx_t)
     D  i_name                             const like(wsdl_path_t)
     D  i_pBuffer                      *   const
     D  i_size                       10I 0 const
     D  i_contentType                      const like(wsdl_contentType_t)
     D  i_transferEncoding...
     D                                     const like(
     D                                           wsdl_contentTransferEncoding_t)
     D                                           options(*nopass: *omit)
     D  i_targetCcsid                10I 0 const options(*nopass: *omit)
      *
      *  Return value
     D partID          S                   like(wsdl_partID_t) inz
      *
      *  Parameter positions
     D p_transferEncoding...
     D                 C                   6
     D p_targetCcsid   C                   7
      *
      *  Optional parameters
     D transferEncoding...
     D                 S                   like(i_transferEncoding)
     D targetCcsid     S                   like(i_targetCcsid)
      *
      *  Local fields
     D hDataSource     S                   like(wsdl_hDataSource_t)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

 B01     if (%parms() >= p_transferEncoding and
             %addr(i_transferEncoding) <> *NULL);
            transferEncoding = i_transferEncoding;
 X01     else;
            transferEncoding = WSDL_MIME_BINARY;
 E01     endif;

 B01     if (%parms() >= p_targetCcsid and %addr(i_targetCcsid) <> *NULL);
            targetCcsid = i_targetCcsid;
 X01     else;
            targetCcsid = -1; // Binary data, no character translation
 E01     endif;

         hDataSource = ManagedMemoryDataSource_new();
         ManagedMemoryDataSource_setBuffer(
            hDataSource: i_name: i_pBuffer: i_size: i_contentType: targetCcsid);

         partID = MessageContext_addAttachment(
                        i_hMsgCtx: hDataSource: transferEncoding: '');

         return partID;

      /end-free
     P                 E
      *
      * =====================================================================
      *   Internal procedure to get the endpoint.
      * =====================================================================
     P getEndpoint...
     P                 B
     D                 PI         32767A          varying
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         return g_url;

      /end-free
     P                 E
      *
      * =====================================================================
      *   Internal procedure to set the endpoint.
      * =====================================================================
     P setEndpoint...
     P                 B
     D                 PI
     D  i_url                     32767A   const varying  options(*varsize)
      * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      /free

         g_url = %subst(i_url: 1: %len(i_url));

      /end-free
     P                 E
      *
